### PR TITLE
US-112 Merging new costumer flow

### PR DESCRIPTION
**Pull request by ademcigdem**

### CODE REVIEW

**Comment by idrisdogruoz** [comment]
deneme

**Review by IrfanAzim34 — APPROVED** [review]

**Review by nevzattalhaozcan — APPROVED** [review]

**Review by samur79 — APPROVED** [review]
all done

**Review by hasanaliaksoy — APPROVED** [review]

**Review by HarunGumusPhD — APPROVED** [review]
its ok

**Review by kesezgin — APPROVED** [review]
Ok

**Pull request merged**
