### PR TITLE
AA-123 Adding Practice page

### PR DESCRIPTION
**Pull request by ademcigdem**

### CODE REVIEW

**Comment by mrFaruq** [comment]
Go ahead. Done.

**Comment by ecaliskanunal** [comment]
Awesome work!

**Comment by Zorlu-Test** [comment]
Well done :)

**Comment by fikretellek** [comment]
nice

**Review by muhammedalkis — APPROVED** [review]

**Review by GokceKochan — APPROVED** [review]
perfect

**Review by AndrianHrisotimos — APPROVED** [review]
Well done

**Comment by GokceKochan** [comment]
good work

**Review by AndrianHrisotimos — COMMENTED** [review]
All aproved

**Pull request merged**
