### PR TITLE
update ihsan

### PR DESCRIPTION
**Pull request by ihsankykc**

### CODE REVIEW

**Comment by berkarcan** [comment]
You are welcome to eu7

**Comment by orhncankaya** [comment]
Hello Guys

**Review by berkarcan — COMMENTED** [review]
God job. Bravissimo

**Review by IntigamQATester — COMMENTED** [review]
good job

**Review by ademcigdem — APPROVED** [review]
congt

**Review by ihsankykc — COMMENTED** [review]
some comment

**Review by Samrasky — COMMENTED** [review]
Very well

**Review by orhncankaya — COMMENTED** [review]
I checked

**Review by firatguzel — COMMENTED** [review]
ok

**Pull request merged**
